version: '3.8'

services:
  tenzro-core:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - STORAGE_PATH=/data/storage
      - NETWORK_BOOTSTRAP=bootstrap.tenzro.network
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - tenzro-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  tenzro-core-prod:
    build:
      context: .
      target: production
    environment:
      - NODE_ENV=production
      - STORAGE_PATH=/data/storage
      - NETWORK_BOOTSTRAP=bootstrap.tenzro.network
    ports:
      - "8080:8080"
    networks:
      - tenzro-network
    volumes:
      - storage-data:/data/storage
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  tenzro-network:
    driver: bridge

volumes:
  storage-data: